ARG Version
FROM almalinux:${Version:-8}
ARG COURSE="Docker" \
    TRAINER="Sivakumar" \
    DUR="10HRS" \
    AUTHOR="joindevops"

RUN echo "TRAINER IS ${TRAINER}, Version is ${Version}"
CMD ["sleep", "200"]